### PR TITLE
Add Docker Support

### PR DESCRIPTION
**Pull request by H4R0**

### CODE REVIEW

**Comment by H4R0** [comment]
It would be great if you would merge the pr and then do a change to readme.md and push it.

On every push to your source respository the container should be automatically be rebuilt within 1 hour.

**Comment by Lazza** [comment]
Thank you for your contribution! 😄

**Comment by Lazza** [comment]
@H4R0 will this still work with Python3?

I am wondering whether it is advisable to keep this in the official repository or not.

**Comment by H4R0** [comment]
I don't know how removing the Dockerfile from master will affect my fork sync and docker builds.

I created a pull request for now. https://github.com/Lazza/RecuperaBit/pull/77

Whether you merge or remove the Dockerfile is up to you.

I bumped pypy and added a smoke test.

**Pull request merged**
