### PR TITLE
[WIP] Change code to run with Python 3

### PR DESCRIPTION
**Pull request by NicolasCARPi**
Hello,

As discussed [here](https://github.com/Lazza/RecuperaBit/issues/59#issuecomment-547173042), I made a python3 compatible version (see https://pythonclock.org/).

The code runs, I believe I changed all the necessary bits and pieces so it runs. BUT, and it's a big but, it seems it doesn't manage to recover partitions.

So please have a look at the code and try it out on real data and let me know if you find something. Because I'm not familiar with the codebase, I might have missed something.

~Nico

### CODE REVIEW

**Comment by Lazza** [comment]
> see https://pythonclock.org/

Porting RecuperaBit to Python 3 might take any arbitrary amount of time, so I would say that it needs to be done properly regardless on when they plan to stop updating Python 2.

**Comment by NicolasCARPi** [comment]
Sure, no problem! Here I just wanted to facilitate the work by making sure the software globally runs with python3, but I realize the inner parts might take more time to get updated!

At least now there is a basis for the porting :)

**Comment by Lazza** [comment]
> Here I just wanted to facilitate the work 

I understand and this is much appreaciated, thank you for what you have done so far!

**Comment by NicolasCARPi** [comment]
Superseeded by #73

**Pull request closed without merging**
