### PR TITLE
Python3 Support

### PR DESCRIPTION
**Pull request by Maxqia**
This replaces #63.
Seems to be fully working, but it could do with more testing.

### CODE REVIEW

**Comment by Lazza** [comment]
First of all, thank you for your very important contribution.

I just wanted to say "sorry" because I have not had the time to review it and I feel a bit guilty about it. This period has been (and still is) super busy with work and other personal stuff.

I really hope to be able to review it carefully. Please don't assume that your contribution is not appreciated...

**Comment by Lazza** [comment]
@NicolasCARPi I was wondering if maybe you would like to check this out as well.

**Comment by NicolasCARPi** [comment]
@Lazza I think @Maxqia took my changes as a base and added more changes. I'll just close mine because this seems more "finished".

**Review by Lazza — APPROVED** [review]
Excellent job

**Comment by Lazza** [comment]
@Maxqia thank you again for your contributions.

Please let me reiterate my apologies for the late feedback. You have done a very appreciated task of migrating this to Python 3. I will check out if some optimizations can be done, but for now it all seems to work.

**Comment by Lazza** [comment]
Also thanks to @NicolasCARPi and other contributors.

**Pull request merged**
