### PR TITLE
Make it clear that compressed NTFS is not supported

### PR DESCRIPTION
**Pull request by NicolasCARPi**
See https://github.com/Lazza/RecuperaBit/issues/67#issuecomment-574362115

### CODE REVIEW

**Comment by NicolasCARPi** [comment]
Ok, rephrased it. I hesitated to add "If you have deep knowledge of the inner workings of file compression on NTFS file system, your help would be appreciated, as available documentation is quite sparse on the topic.". What do you think?

**Comment by Lazza** [comment]
> I hesitated to add "[...]". What do you think?

I like this addition.

**Comment by NicolasCARPi** [comment]
Done!

**Comment by Lazza** [comment]
Thank you!

**Pull request merged**
