### PR TITLE
Docker python3 support

### PR DESCRIPTION
**Pull request by H4R0**

### CODE REVIEW

**Comment by H4R0** [comment]
Restored DFR-04 test image with python3 container.

Everything working.

**Comment by NicolasCARPi** [comment]
A few details:

- use python image instead of debian
- pin the image to python 3.9
- use alpine image (3.9-alpine) if possible
- the LABEL instruction is wrong, it should be:

~~~
LABEL org.label-schema.name="RecuperaBit" \
    org.label-schema.description="A tool for forensic file system reconstruction" \
    org.label-schema.url="https://github.com/Lazza/RecuperaBit/" \
    org.label-schema.vcs-url="https://github.com/Lazza/RecuperaBit/" \
    org.label-schema.maintainer="h4r0" \
    org.label-schema.schema-version="1.0"
~~~

- you can add `--depth 1` to avoid cloning the history in the git command
- `PYTHONIOENCODING utf-8` is not in format ENV=value
- Maybe the default CMD arguments should just be `-h`

**Comment by H4R0** [comment]
- use python image instead of debian
- pin the image to python 3.9
- use alpine image (3.9-alpine) if possible

The docker container uses pypy which is not supported on alpine thus it's based on debian.

The pypy implementation (currently 3.7) is much faster then using python 3.9

Recuperabit and all dependencies are compatible with 3.7

<br/>

- the LABEL instruction is wrong, it should be

Your label recommendation is a community draft not backed by docker and there is only a release candidate for over 4 years now. 

The project is dead.
<br/>

- you can add --depth 1 to avoid cloning the history in the git command

The history is only 280kb in size. I doubt it will grow to a point where it will be of a concern.

<br/>

- PYTHONIOENCODING utf-8 is not in format ENV=value

True, but it has just recently been deprecated and it has not been decided yet if it will actually be removed.

<br/>

- Maybe the default CMD arguments should just be -h

Its a convenient feature, why require the user to type more ?

**Comment by NicolasCARPi** [comment]
@H4R0 I'm okay with all your justifications, I would still use "key=value" for the LABEL!

**Comment by Lazza** [comment]
After more consideration of the subject, I would be inclined to remove the Docker file from the official repository. I do not have the time to maintain a Docker version and sometimes issues arise due to old versions being used via Docker, such as #81.

Would you be OK with creating **your own repo** for a Docker-based RecuperaBit distribution?

I could add a note in the README file mentioning it as a third-party provided Docker image.

**Comment by H4R0** [comment]
Sure no problem

**Comment by H4R0** [comment]
https://github.com/Lazza/RecuperaBit/pull/83

**Comment by Lazza** [comment]
Thank you for your understanding and for taking the time to even prepare a PR. 👍 

If you make a separate repository I can link it into the README.

**Pull request closed without merging**
